/**
 * Creates array with values generated by callbackFn
 * @param arrayLength - length of new array
 * @param callbackFn - callback for each new item of array
 * @returns filled array
 */
const createFilledArray = <TItem>(
  arrayLength: number,
  callbackFn: (value: TItem, index: number) => TItem
) => Array.from(Array(arrayLength), callbackFn);

export { createFilledArray as default };
